DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    brand_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    price_list BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    priority INT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    curr VARCHAR(3) NOT NULL
);
